### ISSUE TITLE
Expecting 'FormAI-v2 Dataset' update

### ISSUE THREAD

**Issue by SwtWld** [FormAI-Dataset/FormAI-dataset#1]
Just read the paper "Do Neutral Prompts Produce Insecure Code? FormAI-v2 Dataset: Labelling Vulnerabilities in Code Generated by Large Language Models" ,looking forward to the FormAI-v2 dataset going live.

**Comment by FormAI-Dataset** [comment]
Thank you for waiting! We are pleased to announce that FormAI-v2 has just been released and is now ready for use.
